// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/session-detail/CleanPremium.tsx": () => import("../components/mockups/session-detail/CleanPremium.tsx"),
  "./components/mockups/session-detail/Current.tsx": () => import("../components/mockups/session-detail/Current.tsx"),
  "./components/mockups/session-detail/LearningTimeline.tsx": () => import("../components/mockups/session-detail/LearningTimeline.tsx"),
  "./components/mockups/session-detail/ModernCards.tsx": () => import("../components/mockups/session-detail/ModernCards.tsx")
};
